export const CALCULATION_CONSTANTS = {
     ONE_TO_FOUR_BASE: 3.26,
     FOUR_TO_SEVEN_BASE: 6.63,
     PER_KM_ONE_TO_FOUR: 2.4,
     PER_KM_FOUR_TO_SEVEN: 3.02,
     PER_MIN_ONE_TO_FOUR: 0.4,
     PER_MIN_FOUR_TO_SEVEN: 0.45,
}




